reviews/scenarios
UdL-EPS-SoftArch/mycircular-api pull request #12
Opened 2022-10-13 15:48 UTC by gugabs

2022-10-13 15:58 UTC, bergacat1 requested changes

2022-10-13 15:58 UTC, bergacat1 commented on src/main/java/cat/udl/eps/softarch/demo/domain/Review.java
> +    private Date when = new Date();
Use ZonedDateTime instead.

2022-10-13 15:58 UTC, bergacat1 commented on src/test/resources/features/SubmitReview.feature
> +    And I can login with username "user0" and password "password"
Background is like a `Given` that will be executed before each test. It's not necessary to do checks with `When` and `Then`

2022-10-13 15:58 UTC, bergacat1 commented on src/test/resources/features/SubmitReview.feature
> +    Then The response code is 400
These tests won't pass yet. You could comment them using `#`

2022-10-18 13:55 UTC, rogargon commented on tepDefs.result = stepDefs.mockMvc.perform(
> +[33mcommit 90933e646c98f9ffd64068e918c2746d5cad73be[m[33m ([m[1;36mHEAD -> [m[1;32mreview[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m, [m[1;32mmain[m[33m)[m
This text shouldn't be here!!!

2022-10-18 13:55 UTC, rogargon commented on .authenticate()))
> +
This text shouldn't be here!!!

2022-10-18 14:10 UTC, rogargon approved these changes

2022-10-18 14:11 UTC, merged